version: '3'

volumes:
  data-volume:

services:
  postgres:
    image: postgres:10.5
    volumes:
      - data-volume:/var/lib/db
    environment:
      POSTGRES_PASSWORD: example

  web:
    build: .
    image: webapp:latest
    links:
      - postgres
    ports:
      - "80:5000"
